### ISSUE TITLE
another plaintext password in src/main/resources/jdbc.properties

### ISSUE THREAD

**Issue by jummy0** [PHSCDC/itocdc-2016-www#14]
line 4

**Comment by majiru** [comment]
So, just to make this clear. This can not be grabbed via the web browser, correct? The only way for someone to view this code would be to either  shifting through the war file or the source code correct? If so, it should work fine from a security standpoint. All we could do would be move the plain text somewhere else but would it sill get linked into the .war file?  I'm not to certain on the implications of this but if we can delete the source code off the machine at the competition and just manage the .war file perms right than I don't see the issue being too high here.  Again, I'm not too familiar with the code base, but those were just some of my thoughts.

**Comment by ngiddings** [comment]
@sinfulspartan This is true; the password will not be grabbed by the browser. Considering that this is a config file, I don't see this as a problem. However, it also needs to be tracked by Git during development, so it is important that the production environment has a unique password (we can keep 'cdc' for development). I do maintain that actual source code should not contain sensitive information, and there are instances of passwords in the Java source. That is a problem.
