### ISSUE TITLE
Non-admins can change any the password of any other user

### ISSUE THREAD

**Issue by ngiddings** [PHSCDC/itocdc-2016-www#22]
The same change password function is used for both the admin panel and individual account panels. If a regular user submits a username other than their own, they can reset the password of any desired user.

The solution is to use a seperate function to change one's own password, and that function can be written to only change the password of the current session. Then we can link to that function in the profile page.

Does anyone know how to obtain session information from Java?

**Comment by jummy0** [comment]
This can be used to set every user's password simultaneously if the username is set to `' OR true;#`.

**Comment by ngiddings** [comment]
We found out how to get a username from a an auth session. Therefore, after adapting the code, we can completely remove the username from the password/email change form.

**Comment by jummy0** [comment]
Potential alternate/supplementary fix: require users to give their current password before changing it.

**Comment by ngiddings** [comment]
FINALLY FIXED IM SO TIRED
