### ISSUE TITLE
How does the login form work?

### ISSUE THREAD

**Issue by jummy0** [PHSCDC/itocdc-2016-www#23]
`src/main/webapp/WEB-INF/jsp/login.jsp` contains a form that posts to `/login`.
`src/main/java/org/iseage/ito/controller/MainController.java` contains one mapping for `/login`, and nothing else.
What **_is**_ `/login`, and how does it handle sessions?

**Comment by ngiddings** [comment]
Spring Boot has a framework that allows information to be requested about the auth state.

**Comment by ngiddings** [comment]
Jimmy and I have learned how sessions are handled in Spring. If anyone else really needs this information, just ask us.
