### ISSUE TITLE
Session hijacking

### ISSUE THREAD

**Issue by jummy0** [PHSCDC/itocdc-2016-www#25]
1. obtain other user's session id
2. change your session id to the obtained session id
3. upload memes to screenshot page (optional; recommended)

proposed fix: make it so ip can't change within a session

**Comment by ngiddings** [comment]
Requester's IP can be obtained from the auth session. As stated in the proposed fix, we can determine a change in IP and deauth the session. However, because of IP spoofing, this is not enough. We still need to protect the session ID on unsecured connections (or begin using HTTPS on port 80).

**Comment by ngiddings** [comment]
I've merged a tenative fix, but it has yet to be tested adequately.

**Comment by ngiddings** [comment]
So far as I can tell this issue is "fixed". While I do believe there is still a window of attack here, the threat is severely diminished. I have no time to properly test this, however, so this issue may need repoened.
