### ISSUE TITLE
WebConfig.java | 2 image resource handlers

### ISSUE THREAD

**Issue by svongpanya** [PHSCDC/itocdc-2016-www#4]
17 registry.addResourceHandler("/img/**").addResourceLocations("file:" + Application.getUploadDir());
18 registry.addResourceHandler("/css/**").addResourceLocations("WEB-INF/css/");
19 registry.addResourceHandler("/js/**").addResourceLocations("WEB-INF/js/");
20 registry.addResourceHandler("/simg/**").addResourceLocations("WEB-INF/img/");

On lines 17 & 20, should there be 2 resource handlers for images (img and simg)?

**Comment by ngiddings** [comment]
Yes, there should be. Take a look at the mappings--they are different web addresses and lead to different points in the filesystem. Therefore, they are not redundant. Taking a deeper look, I found that /img/ is mapped to user-uploads (such as screenshots), while /simg/ maps to images packaged with the web app.
