### ISSUE TITLE
There is a multiple lines of "true," NOT GOOD

### ISSUE THREAD

**Issue by Dabomb1000** [PHSCDC/itocdc-2016-www#5]
```
userDetails = new org.springframework.security.core.userdetails.User(
                user.getUsername(),
                user.getPassword().toLowerCase(),
                true,
                true,
                true,
                true,
                getAuthorities(user.getAccess())
```

**Comment by ngiddings** [comment]
This constructor is part of the Spring Security library. Method signature is as follows:

User(String username, String password, boolean enabled, boolean accountNonExpired, boolean credentialsNonExpired, boolean accountNonLocked, Collection<? extends GrantedAuthority> authorities);

Although this indicates a lack of cohesion regarding this class in my opinion, it is irrelevant to our site.
